#!/bin/bash
for f in *; do
    if [ -d "$f" ]; then
        # $f is a directory
        if [[ $f = @* ]]; then # directory starts with @
          for dir in $f/*/; do echo "$dir"; done
        else
          echo $f
        fi
    fi
done